name: 1-runner-2-deployers
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  buildimg:
    runs-on: run1
    environment: 1r2de
    steps:
      - uses: actions/checkout@v4
      
      - name: build-frontend-image
        working-directory: ./frontend
        run: |
          docker rmi fimg || true
          docker rmi koak/1r2d:frontend || true
          docker build -t fimg .
          echo "${{ secrets.DHPASS }}" | docker login -u "${{ secrets.DHUSER }}" --password-stdin
          docker tag fimg koak/1r2d:frontend
          docker push koak/1r2d:frontend 
      
      - name: deploy-image-in-ps1
        run: |
         eval "$(ssh-agent -k)" || true
         eval "$(ssh-agent -s)"
         ssh-add ~/.ssh/adv
          ssh -T "${{ secrets.SSHUSER }}"@"${{ secrets.SSHHOST }}"
          echo "${{ secrets.DHPASS }}" | docker login -u "${{ secrets.DHUSER }}" --password-stdin
          docker rmi koak/1r2d:frontend || true
          curl -o docker-compose.yml https://raw.githubusercontent.com/koakko/1r2d/refs/heads/main/docker-compose.yml
          docker stop cfend || true
          docker rm cfend || true
          docker compose up -d